### ISSUE TITLE
task.shift-recurrence not work properly

### ISSUE THREAD

**Issue by sakarimov** [GothenburgBitFactory/taskwarrior#2731]
![image](https://user-images.githubusercontent.com/5676876/153690304-4a2af9c9-3123-4f22-8a17-7d03535fd394.png)

i make tasks that have schedule, wait and until attributes, i got strange behaviour with the tasks, then i delete until and schedule atributes, everything goes well, but after that i read that it can be done by using [task.shift-recurrence](https://github.com/tbabej/task.shift-recurrence) hook, but when i try to modify my task back to have schedule and until, i got an error above, is there something wrong with the command? or i just have to make new tasks to make it works, thank you

**Comment by sakarimov** [comment]
UPDATE

i re-check the documentation, and re-install the hook like instructed in the documentation. but i still get an error like follows
```
Traceback (most recent call last):
  File "/home/sulthan/.task/hooks/on-add-pirate", line 46, in <module>
    hook(task)
  File "/home/sulthan/.task/hooks/shift-recurrence/pirate_add_shift_recurrence.py", line 25, in hook_shift_recurrence
    parent = tw.tasks.get(uuid=task['parent']['uuid'])
  File "/home/sulthan/.local/lib/python3.10/site-packages/tasklib/task.py", line 548, in get
    num = len(clone)
  File "/home/sulthan/.local/lib/python3.10/site-packages/tasklib/task.py", line 471, in __len__
    self._result_cache = list(self.__iter__())
  File "/home/sulthan/.local/lib/python3.10/site-packages/tasklib/task.py", line 476, in __iter__
    self._result_cache = self._execute()
  File "/home/sulthan/.local/lib/python3.10/site-packages/tasklib/task.py", line 508, in _execute
    return self.backend.filter_tasks(self.filter_obj)
  File "/home/sulthan/.local/lib/python3.10/site-packages/tasklib/backends.py", line 334, in filter_tasks
    for line in self.execute_command(args):
  File "/home/sulthan/.local/lib/python3.10/site-packages/tasklib/backends.py", line 297, in execute_command
    raise TaskWarriorException(error_msg)
tasklib.backends.TaskWarriorException: TASKDATA override: /home/sulthan/.task
Configuration override rc.confirmation=no
Configuration override rc.dependency.confirmation=no
Configuration override rc.recurrence.confirmation=no
Configuration override rc.json.array=off
Configuration override rc.bulk=0
Configuration override rc.data.location=/home/sulthan/.task
Configuration override rc.recurrence=no
Configuration override rc.hooks=no
Unable to find report that matches '3d0a976e-a658-4ac1-beca-558681a12977'.
Command used: task rc.confirmation=no rc.dependency.confirmation=no rc.recurrence.confirmation=no rc.json.array=off rc.bulk=0 rc.data.location=/home/sulthan/.task rc.recurrence=no rc.hooks=no export 3d0a976e-a658-4ac1-beca-558681a12977
Task 802d0829 'test_rec_3' expired and was deleted.
Warning: You have specified that the 'wait' date is after the 'scheduled' date.
Hook Error: Expected feedback from failing hook script: on-add-pirate

```
i tried so many time, by making fake task that has 'wait', 'schedule', and 'until' properties, but the result is still the same error. i guess i just have to wait for [Recurrence Overhaul](https://github.com/GothenburgBitFactory/taskwarrior/projects/6) project to be done

**Comment by djmitche** [comment]
Apologies, we don't really provide support for hooks in this repo.
